// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enxrpnhcetbgoicfsqqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVueHJwbmhjZXRiZ29pY2ZzcXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTk5MjMsImV4cCI6MjA2MDU3NTkyM30.DmxnFczU2WWhx38JibU0UTFjP5xy3MRksmg3H5xXmWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);